### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by davemevans** [bitmovin/bitmovin-javascript#94]
When attempting to install the client for modification to add missing endpoints after cloning from github. Note that simply installing the client direct from npm does work.

Occurs on both Windows and Ubuntu during `npm install`.

```
$ cross-env NODE_ENV=development webpack --config=./webpack4.config.js
C:\work\bitmovin-javascript\node_modules\webpack-cli\bin\config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (C:\work\bitmovin-javascript\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at C:\work\bitmovin-javascript\node_modules\webpack-cli\bin\webpack.js:60:27
    at Object.<anonymous> (C:\work\bitmovin-javascript\node_modules\webpack-cli\bin\webpack.js:515:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
error Command failed with exit code 1.
```

**Comment by davemevans** [comment]
This can be fixed by upgrading webpack-cli to v3 as described at https://github.com/webpack/webpack/issues/8082.
